[phases.setup]
nixPkgs = ["...", "nss", "alsa-lib", "atk", "cups", "libdrm", "gtk3", "pango", "cairo", "libXcomposite", "libXcursor", "libXdamage", "libXext", "libXfixes", "libXi", "libXrandr", "libXrender", "libxshmfence", "libXtst", "mesa", "dbus"]

[phases.build]
cmds = ["npm install", "npx puppeteer browsers install chrome"]

[start]
cmd = "npm start"
